#!/bin/bash

## Enable LTTng events and strart tracing 
 lttng create
 lttng enable-channel ss -u --subbuf-size 8M;
 lttng add-context -u -t vtid -c ss; 
 lttng enable-event -u -a -c ss
 lttng start
 
 
## Then run you php script, do your requests, commands , etc.
 #...
 
 
## Finally, after finishing the tracing, you should stop the trace and open the resulting events: 
 # lttng stop
 # ltng view
 
